-- Generated by scripts/gen-seed.mjs. Placeholder catalogue: replace with the real stock.
insert into public.products (slug, name, description, category, price_kobo, stock) values
  ('toyota-camry-2019', 'Toyota Camry SE 2019', 'Foreign-used (Tokunbo) Camry SE, automatic, 2.5L, clean title, leather interior, reverse camera. Full inspection report on request.', 'Cars', 2800000000, 2),
  ('lexus-es350-2018', 'Lexus ES 350 2018', 'Foreign-used ES 350 in black, sunroof, heated seats, low mileage, accident-free.', 'Cars', 3200000000, 1),
  ('honda-accord-2017', 'Honda Accord Sport 2017', 'Nigerian-used Accord Sport, automatic, excellent fuel economy, all documents complete.', 'Cars', 1800000000, 3),
  ('mercedes-c300-2017', 'Mercedes-Benz C300 2017', '4MATIC C300, black on black, panoramic roof, Burmester audio, full service history.', 'Cars', 3500000000, 1),
  ('toyota-highlander-2018', 'Toyota Highlander XLE 2018', 'Three-row Highlander XLE, V6, leather seats, ideal for family and business use.', 'SUVs & Trucks', 3800000000, 2),
  ('lexus-rx350-2016', 'Lexus RX 350 2016', 'Foreign-used RX 350, AWD, navigation, clean interior and a smooth ride.', 'SUVs & Trucks', 2900000000, 2),
  ('toyota-hilux-2020', 'Toyota Hilux 4x4 2020', 'Double-cab Hilux 4x4, diesel, rugged and ready for work or the open road.', 'SUVs & Trucks', 4500000000, 1),
  ('honda-cg125', 'Honda CG 125 Motorcycle', 'Reliable, fuel-efficient commuter bike. Brand new, with registration support.', 'Motorcycles', 145000000, 10),
  ('bajaj-boxer-150', 'Bajaj Boxer 150', 'Tough and affordable workhorse for daily trips and deliveries. Brand new.', 'Motorcycles', 110000000, 12),
  ('tvs-apache-160', 'TVS Apache RTR 160', 'Sporty 160cc street bike with disc brakes and a digital console.', 'Motorcycles', 180000000, 6),
  ('yamaha-mt07-2021', 'Yamaha MT-07 2021', 'Foreign-used 689cc naked sport bike, low mileage, black and gold custom finish.', 'Motorcycles', 950000000, 1),
  ('mountain-bike-275', 'Mountain Bike 27.5"', '21-speed aluminium-frame mountain bike with front suspension and disc brakes.', 'Bicycles', 35000000, 15)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, category = excluded.category,
  price_kobo = excluded.price_kobo;
