// Generates supabase/seed.sql from src/lib/catalog.json. Run: node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const items = JSON.parse(readFileSync("src/lib/catalog.json", "utf8"));
const rows = items.map((p) =>
  `  (${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${q(p.category)}, ${p.price_kobo}, ${p.stock})`).join(",\n");
writeFileSync("supabase/seed.sql",
`-- Generated by scripts/gen-seed.mjs. Placeholder catalogue: replace with the real stock.
insert into public.products (slug, name, description, category, price_kobo, stock) values
${rows}
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, category = excluded.category,
  price_kobo = excluded.price_kobo;
`);
