// Generates supabase/seed.sql from src/lib/catalog.json. Run: node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? "null" : Number(v));
const items = JSON.parse(readFileSync("src/lib/catalog.json", "utf8"));
const rows = items.map((p) =>
  `  (${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${q(p.category)}, ${p.price_kobo}, ${p.stock}, ` +
  `${n(p.year)}, ${n(p.mileage_km)}, ${q(p.condition)}, ${q(p.image)}, ${q(p.cutout)})`).join(",\n");
writeFileSync("supabase/seed.sql",
`-- Generated by scripts/gen-seed.mjs. Placeholder catalogue: replace with the real stock.
-- Run supabase/schema.sql first (it adds the year / mileage_km / condition / cutout_url columns).
insert into public.products (slug, name, description, category, price_kobo, stock, year, mileage_km, condition, image_url, cutout_url) values
${rows}
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, category = excluded.category,
  price_kobo = excluded.price_kobo, year = excluded.year, mileage_km = excluded.mileage_km,
  condition = excluded.condition, image_url = excluded.image_url, cutout_url = excluded.cutout_url;
`);
